issue106/get_models helper macro
dbt-labs/dbt-codegen pull request #115
Opened 2023-01-30 11:10 UTC by erkanncelen

resolves #

This is a:
- [ ] documentation update
- [ ] bug fix with no breaking changes
- [x] new functionality
- [ ] a breaking change

All pull requests from community contributors should target the `main` branch (default).

## Description & motivation

Added a helper macro named "get_models" in the macros/helpers section. The macro is used to get a list of all models with a specified prefix, in a specified directory.

Example:
codegen.get_models(directory='marts', prefix='fct')

I mainly created this to make generate_model_yaml macro more powerful.

Example:
codegen.generate_model_yaml(
    model_names = codegen.get_models(directory='marts', prefix='fct')

This way we can generate yamls for any set of models in our project.

## Checklist
- [x] This code is associated with an issue (https://github.com/dbt-labs/dbt-codegen/issues/106) which has been triaged and [accepted for development]
(https://docs.getdbt.com/docs/contributing/oss-expectations#pull-requests). 
- [x] I have verified that these changes work locally
- [x] I have updated the README.md (if applicable)
- [x] I have added tests & descriptions to my models (and macros if applicable)
- [x] I have added an entry to CHANGELOG.md

2023-01-30 20:23 UTC, joellabes requested changes
Two wee tweaks but otherwise we're good to go!

2023-01-30 20:23 UTC, joellabes commented on README.md
> +) }}
Splitting the macros apart makes it easier to read:

```suggestion
{% set models_to_generate = codegen.get_models(directory='marts','prefix='fct_') %}
{{ codegen.generate_model_yaml(
    model_names = models_to_generate
) }}
```

2023-01-30 20:23 UTC, joellabes commented on integration_tests/tests/test_helper_get_models.sql
> +{{ assert_equal (actual_list | trim, expected_list | trim) }}
```suggestion
{{ assert_equal (actual_list, expected_list) }}
```

The `| trim` filters are unnecessary here - you can't remove whitespace from a list. it's used in other code in these tests because they’re comparing the string values

2023-01-31 09:36 UTC, erkanncelen commented
You are right, I accepted the changes in readme.

And yes, apparently I forgot to delete `| trim`s after I reworked the test.

All done! Thanks @joellabes

2023-02-01 07:27 UTC, joellabes approved these changes

2023-02-01 07:54 UTC, merged