Feature/tables option for codegen
dbt-labs/dbt-codegen pull request #60
Opened 2022-03-08 00:26 UTC by matt-winkler

This is a:
- [ ] bug fix PR with no breaking changes — please ensure the base branch is `main`
- [X] new functionality — please ensure the base branch is the latest `dev/` branch
- [ ] a breaking change — please ensure the base branch is the latest `dev/` branch

## Description & motivation
See (here)[https://github.com/dbt-labs/dbt-codegen/issues]

## Checklist
- [X] I have verified that these changes work locally
- [ ] I have updated the README.md (if applicable) #TODO
- [ ] I have added tests & descriptions to my models (and macros if applicable) #TODO
- [ ] I have added an entry to CHANGELOG.md #TODO

2022-03-14 05:15 UTC, joellabes requested changes
Looking good! A couple of compatibility and testing requests, but otherwise very on board with getting this merged in 🥳

2022-03-14 05:15 UTC, joellabes commented on macros/generate_source.sql
> +{% macro get_tables_in_schema(schema_name, table_pattern, database_name=target.database) %}
If anyone is calling this directly with existing code, adding a new param that doesn't have a default would break it:

```suggestion
{% macro get_tables_in_schema(schema_name, table_pattern='%', database_name=target.database) %}
```

Also worth calling out that by putting this in second position instead of adding it to the end will also be a breaking change for anyone using positional arguments instead of naming them. I think it's the right thing to do because it's then consistent with the dbt_utils macro's default order, but it does mean this will be a minor release instead of a patch release.

2022-03-14 05:15 UTC, joellabes commented on macros/generate_source.sql
> +{% macro get_tables_in_schema(schema_name, table_pattern, database_name=target.database) %}
Thinking about it more, I think it'd be worth adding support for `exclude` while you're here, so that people can use everything that's available to dbt utils.

2022-03-14 05:15 UTC, joellabes commented on integration_tests/tests/test_generate_source_table_pattern.sql
> +{% set actual_source_yaml = codegen.generate_source(raw_schema, table_pattern='data__%') %}
This is the same resulting data as without the table pattern - I think you should add a second seed file prefixed with something that isn't `data__` and add that to the [other test](https://github.com/dbt-labs/dbt-codegen/blob/main/integration_tests/tests/test_generate_source.sql) so that we know this is passing because it's doing the right thing, not just impossible to do the wrong thing.

2022-03-14 05:15 UTC, joellabes commented on CHANGELOG.md
> +# dbt-codegen v0.5.1
This'll be breaking changes so 0.6.0 as discussed below

2022-03-14 16:32 UTC, matt-winkler commented
@joellabes Good feedback! I was wondering about the use of exclude here as well, so went ahead and added that one in + some love on integration tests.

2022-03-22 03:14 UTC, joellabes approved these changes
I like where you've landed with this! Love the pair of test cases with both a specific inclusion and an exclusion 😍 

Let's ship it 🚢

2022-03-22 03:14 UTC, merged