New functionality - Retrieve the description for identical column names from upstream models
dbt-labs/dbt-codegen pull request #61
Opened 2022-03-30 12:11 UTC by b-per

This is a:
- [ ] bug fix PR with no breaking changes — please ensure the base branch is `main`
- [x] new functionality — please ensure the base branch is the latest `dev/` branch
- [ ] a breaking change — please ensure the base branch is the latest `dev/` branch

## Description & motivation
When using the macro `generate_model_yaml` it can be cumbersome to have to copy/paste the description of the columns from the upstream models, especially when many models are joined together.

The new feature accessible via the flag `upstream_descriptions=True` (defaulted to False) parses the Jinja graph to retrieve existing descriptions in parent models.

An example of output is the following, when the upstream model has an existing description of `description column a`:
![image](https://user-images.githubusercontent.com/8754100/160831041-41b37910-0a24-4c50-ab98-01afc33342c7.png)

I am not too sure where I should add the entry in `CHANGELOG.md`

## Checklist
- [x] I have verified that these changes work locally
- [x] I have updated the README.md (if applicable)
- [x] I have added tests & descriptions to my models (and macros if applicable)
- [ ] I have added an entry to CHANGELOG.md

2022-05-13 13:17 UTC, dbeatty10 commented
Thanks for this awesome enhancement, @b-per! 💪 

Integration test and readme looks great.

Two things for you to do:
1. I left feedback on two very small things
1. Example for adding CHANGELOG entry below

## Changlog entry
> I am not too sure where I should add the entry in CHANGELOG.md

You can follow [this](https://github.com/dbt-labs/dbt-utils/blob/f4c4ae6ef1e70d04a2f96bbc0fa7b5de7539d4c9/CHANGELOG.md?plain=1) pattern for adding to the changelog. Something like this:
```
# Unreleased
## New features
- Awesome description of fabulous new feature here ([#61](https://github.com/dbt-labs/dbt-utils/pull/61)) 
```

2022-05-13 13:53 UTC, dbeatty10 requested changes

2022-05-13 13:53 UTC, dbeatty10 commented on macros/helpers/helpers.sql
> +{# build a global dictionnary looping through all the direct parents models #}
```suggestion
{# build a global dictionary looping through all the direct parents models #}
```

2022-05-13 15:13 UTC, dbeatty10 approved these changes
Looking good!

Could you take a look at the build in CircleCI? Looks like `test_generate_model_yaml_upstream_descriptions` isn't passing.

2022-05-16 17:00 UTC, b-per commented
I got quite puzzled about why the test was passing locally but not in CI, before I realized that I needed to add a `dbt run` to the CI step to get `codegen` to list the column of the downstream model.

It should be all-good now!

2022-05-17 12:10 UTC, dbeatty10 approved these changes
Nice catch, @b-per 

👍 Everything looks good.

2022-05-17 12:10 UTC, merged