Add include_data_types flag to generate_source macro
dbt-labs/dbt-codegen pull request #76
Opened 2022-08-17 10:05 UTC by GSokol

This is a:
- [ ] bug fix PR with no breaking changes — please ensure the base branch is `main`
- [x] new functionality — please ensure the base branch is the latest `dev/` branch
- [ ] a breaking change — please ensure the base branch is the latest `dev/` branch

## Description & motivation
Closes https://github.com/dbt-labs/dbt-codegen/issues/75

## Checklist
- [x] I have verified that these changes work locally
- [x] I have updated the README.md (if applicable)
- [ ] I have added tests & descriptions to my models (and macros if applicable)
- [ ] I have added an entry to CHANGELOG.md

2022-08-24 10:04 UTC, GSokol commented
@clrcrl or @matt-winkler, could you please take a look?

2022-08-29 06:22 UTC, GSokol commented
Maybe, @dbeatty10 could take a look?

2022-08-29 16:38 UTC, dbeatty10 requested changes
@GSokol makes sense for codegen to have an option to include the [optional `data_type` metadata field](https://docs.getdbt.com/reference/resource-properties/columns) -- thanks for opening!

I added some comments on some implementation details for the integration tests for you to explore. Could you take a look and see if any of them work?

Your current implementation is reasonable with a small footprint, and we can move forward with it if my suggested ideas all end up being dead-ends.

2022-08-29 16:38 UTC, dbeatty10 commented on integration_tests/tests/test_generate_source_all_args.sql
> +            data_type: {{ text_type_value(1) }}
I'm guessing the integration tests are tricky in this case because it's probably trying to do an _exact_ string match?

We generally try to avoid `if target.type == ` ... whenever possible, but sometimes it isn't avoidable or is unreasonably complicated). I'd love to explore our alternatives (which you may have already considered).

### Ideas for avoiding `target.type ==`

#### Idea 1
[Relations and Columns](https://docs.getdbt.com/reference/dbt-classes) are the two main dbt classes that can be utilized to create objects on-the-fly.

One big advantage of using these is that they have database adapter-specific implementations, so can often handle the arcane details (like data type syntax).

I was originally wondering if the [Column.create](https://github.com/dbt-labs/dbt-core/blob/a642b20abc3b729cb04fd0616db065c5d0c19868/core/dbt/adapters/base/column.py#L26-L29) method could be used in conjunction with applicable [cross-database data type functions](https://docs.getdbt.com/reference/dbt-jinja-functions/cross-database-macros#data-type-functions).

Something like this:
```
data_type: {{ api.Column.create(dtype=type_string(), char_size=2) }}
```

Unfortunately, that won't work because `Column.create` doesn't have any size parameters 😭.

#### Idea 2
There's also a [Column.from_description](https://github.com/dbt-labs/dbt-core/blob/a642b20abc3b729cb04fd0616db065c5d0c19868/core/dbt/adapters/base/column.py#L122-L159) method. I'm wondering if it could be used in conjunction with applicable [cross-database data type functions](https://docs.getdbt.com/reference/dbt-jinja-functions/cross-database-macros#data-type-functions) instead.

Something like this for text/string of length 1:
```
data_type: {{ api.Column.from_description(name=none, raw_data_type=type_string() ~ "(1)") }}
```

Kinda hacky! 😅 

Integer columns would be more straight-forward:
```
data_type: {{ api.Column.from_description(name=none, raw_data_type=type_int()) }}
```
Or more direct and succinct:
```
data_type: {{ api.Column.create(type_int()) }}
```

Could you give Idea 2 a try and see if it works or not?

(If this works, you could put the `api.*` jazz within the macros you already created like `integer_type_value`.)

As a follow-up, we could also [create a feature request](https://github.com/dbt-labs/dbt-core/issues/new/choose) to add optional `char_size`, `numeric_precision`, and `numeric_scale` parameters to `Column.create`.

2022-08-31 15:17 UTC, GSokol commented on integration_tests/tests/test_generate_source_all_args.sql
> +            data_type: {{ text_type_value(1) }}
Oh, thank you @dbeatty10 for such a detailed answer. I have doubts about combining sized types, aka `NUMBER(38,0)` and `CHARACTER VARYING(8)` with unsized types aka `INT64`, `INTEGER`, `STRING`, `TEXT`. I mean, the problem here is not in platform-specific type namings, but in the ways how different databases gather types during CSV uploads.

2022-08-31 16:13 UTC, dbeatty10 commented on integration_tests/tests/test_generate_source_all_args.sql
> +            data_type: {{ text_type_value(1) }}
Yeah, that's totally understandable that mixing size-specific and unspecified type definitions might not work out.

Here's some simplified pseudo code that _might_ abstract things away from `target.type == "snowflake"`:
```
{%- macro expected_data_type(data_type, size=none) -%}
{%- if size -%}
{{ api.Column.from_description(name=none, raw_data_type=data_type ~ "(" ~ size ~ ")") }}
{%- else -%}
{{ api.Column.create(data_type) }}
{%- endif -%}
{%- endmacro -%}
```

Then it would be used like this (which I didn't try out at all!):
```yaml
data_type: {{ expected_data_type(type_string(), size="1") }}
```

It's okay if we try this out and it doesn't work. Since the code in question is only related to the integration testing, it's probably okay to use specific code like `target.type == "snowflake"`, etc. For regular package code, using `target.type == ` is highly discouraged in favor of [dispatched macros](https://docs.getdbt.com/reference/dbt-jinja-functions/dispatch).

2022-12-08 12:20 UTC, GSokol commented on integration_tests/tests/test_generate_source_all_args.sql
> +            data_type: {{ text_type_value(1) }}
@dbeatty10, I've tried some approaches but failed. Anyway, you already have such dirty tricks in tests [here](https://github.com/dbt-labs/dbt-codegen/blob/main/integration_tests/macros/operations/create_source_table.sql).

2022-12-08 15:03 UTC, dbeatty10 commented on integration_tests/tests/test_generate_source_all_args.sql
> +            data_type: {{ text_type_value(1) }}
Thanks for giving it a shot @GSokol !

Your original implementation is reasonable with a small footprint, and I feel comfortable moving forward with it since it sounds like my suggested ideas all ended up being dead-ends.

2022-12-21 01:30 UTC, dbeatty10 approved these changes
Thanks for your work on this @GSokol ! 🚀

2022-12-21 01:31 UTC, merged