Feature/materialize base models as view
dbt-labs/dbt-codegen pull request #79
Opened 2022-09-16 17:25 UTC by davesgonechina

This is a:
- [ ] bug fix PR with no breaking changes — please ensure the base branch is `main`
- [X] new functionality — please ensure the base branch is the latest `dev/` branch
- [ ] a breaking change — please ensure the base branch is the latest `dev/` branch

## Description & motivation
Add `materialize_as_view` parameter to `generate_base_model` to allow users to choose whether to materialize the model as a table or a view.

## Checklist
- [ ] I have verified that these changes work locally
- [ ] I have updated the README.md (if applicable)
- [ ] I have added tests & descriptions to my models (and macros if applicable)
- [ ] I have added an entry to CHANGELOG.md

2022-11-21 22:03 UTC, joellabes requested changes
Excited to add this option! There's a few pieces of feedback to avoid backwards compatibility issues and make the naming clearer 🙏

2022-11-21 22:03 UTC, joellabes commented on macros/generate_base_model.sql
> +{{ "{{ config(materialized='"+materialization+"') }}" }}
This will need a block that checks whether `materialized` arg is `None`. 

Also I have a slight preference for `~` for concatenation instead of `+`, and a bit of whitespace wouldn't go astray
```suggestion
{{ "{{ config(materialized='" ~ materialization ~ "') }}" }}
```

2022-11-22 16:29 UTC, davesgonechina commented on macros/generate_base_model.sql
> +{{ "{{ config(materialized='"+materialization+"') }}" }}
Done, cheers!

2022-11-23 02:29 UTC, joellabes requested changes
Almost there! It shouldn't provide a materialization in all cases - most files don't actually contain materialization configs and are instead just defined in the project.yml file

2022-11-23 02:29 UTC, joellabes commented on integration_tests/tests/test_generate_base_models_case_sensitive.sql
> +{{ "{{ config(materialized='table') }}" }}
~Why would table be in the expected base model, given that [`None` is the default now](https://github.com/dbt-labs/dbt-codegen/pull/79/files#diff-78b1acd5683e3830da43008af04542174afe76066c07cdfe1fb7645e4bd72eb2R1), and you're not specifying a materialization style [in the macro call](https://github.com/dbt-labs/dbt-codegen/pull/79/files#diff-bc973d38deca00b5b3f4fa14550d32c4c88043a34dafa04e1cedb47a02d16d89R6) above?~

Edit: worked it out, it was being hardcoded below. This should be removed as discussed in bottom comment

```suggestion
```

2022-11-23 02:29 UTC, joellabes commented on macros/generate_base_model.sql
> +    {{ "{{ config(materialized='table') }}" }}
If they don't specify a materialization, you don't need to set one at all here. This is what makes it possible for it to be defined by dbt_project.yml
```suggestion
```

2022-11-23 02:29 UTC, joellabes commented on integration_tests/tests/test_generate_base_models_leading.sql
> +{{ "{{ config(materialized='table') }}" }}
Same here
```suggestion
```

2022-11-23 19:48 UTC, joellabes commented on macros/generate_base_model.sql
> +    {{ "{{ config(materialized='table') }}" }}
Nope - it'll inherit from the user's code in their file.

2022-11-23 22:03 UTC, joellabes approved these changes
🌠 🎉

2022-11-23 22:03 UTC, merged