Feature/generate multiple models yaml
dbt-labs/dbt-codegen pull request #85
Opened 2022-10-24 19:43 UTC by angelica-lastra

This is a:
- [ ] bug fix PR with no breaking changes — please ensure the base branch is `main`
- [x] new functionality — please ensure the base branch is the latest `dev/` branch
- [ ] a breaking change — please ensure the base branch is the latest `dev/` branch

## Description & motivation
closes #68 
Added code that allows for generate_model_yaml to accept multiple model arguments as a list, or one model as a string. 
Updated README to reflect this feature.

## Checklist
- [x] I have verified that these changes work locally
- [x] I have updated the README.md (if applicable)
- [ ] I have added tests & descriptions to my models (and macros if applicable)
- [ ] I have added an entry to CHANGELOG.md

## Other comments

- Should I add an entry to the CHANELOG.md for this?
- Also, I am creating a pull request to merge into dev/ — should this be merged into main/ instead?

2022-10-24 19:56 UTC, bennieregenold7 commented
@angelica-lastra I think there may be something off between this and the branch you're merging into. There are 32 changed files, but if I remember correctly, you only changed one. Should this merge into `dev/0.4.0` or main?

2022-10-24 19:58 UTC, angelica-lastra commented
@bennieregenold7 I think you are right, I got confused because the checklist on the PR said "[x] new functionality — please ensure the base branch is the latest dev/ branch", so I assumed I had to merge there, but main made more sense to me.

2022-10-24 20:06 UTC, angelica-lastra commented
@bennieregenold7 I changed to merge to main and that seemed to address that concern, however, if anyone else has any guidance on this, please let me know!

2022-10-24 20:14 UTC, bennieregenold7 commented on README.md
> +$ dbt run-operation generate_model_yaml --args '{"model_name": ["customers", "orders"]}'
very low impact suggestion: it could or useful to show how to call this macro both ways. Something like this:

```
$ dbt run-operation generate_model_yaml --args '{"model_name": "customers"}'
```
-or-
```
$ dbt run-operation generate_model_yaml --args '{"model_name": ["customers", "orders"]}'
```

2022-10-24 20:23 UTC, angelica-lastra commented on README.md
> +$ dbt run-operation generate_model_yaml --args '{"model_name": ["customers", "orders"]}'
Makes sense, it's helpful to see both cases written out! 
Just added it to the README

2022-10-24 20:32 UTC, bennieregenold7 approved these changes

2022-10-26 17:26 UTC, graciegoheen approved these changes
Awesome work here! Especially love the way you dealt with appending the single model name to an empty list if it's inputed as a string. LGTM!

2022-10-26 19:51 UTC, angelica-lastra commented
> Awesome work here! Especially love the way you dealt with appending the single model name to an empty list if it's inputed as a string. LGTM!

@graciegoheen Thank you so much! I am so excited I have not stopped thinking about this! that particular code you are referring to is all thanks to @bennieregenold7 for catching it and walking me through how to write it!

2022-10-26 22:34 UTC, joellabes reviewed
I'm happy for this to go out as-is, but have a bit of feedback which you can take or leave! lmk what you think.

2022-10-26 22:34 UTC, joellabes commented on macros/generate_model_yaml.sql
> +        {% do model_name_list.append(model_name) %}
```suggestion
        {% set model_name_list=[model_name] %}
```
I think you can do this in one line! (This becomes redundant if you accept my other comment, but is still a fun fact)

2022-10-26 22:34 UTC, joellabes commented on macros/generate_model_yaml.sql
> +{% macro generate_model_yaml(model_name=[], upstream_descriptions=False) %}
It feels weird for this argument to be a singular noun, when it takes an array. 

I would recommend switching this to be `model_names`, and require an array of names even if there's only one to be generated. 

It is _basically fine_ as-is, but I think it'd be more discoverable, and since these are used as one-offs instead of going into automated use cases, I'm not as worried about breaking backwards compatibility. 

This would also let you clean up the code further down because you wouldn't have to check if it's a string and make a list if it is.

2022-11-03 21:29 UTC, angelica-lastra commented on macros/generate_model_yaml.sql
> +{% macro generate_model_yaml(model_name=[], upstream_descriptions=False) %}
thank you @joellabes! I have integrated your comments on my most recent commits!

2022-11-03 21:31 UTC, angelica-lastra commented on macros/generate_model_yaml.sql
> +        {% do model_name_list.append(model_name) %}
good to know!

2022-11-03 21:37 UTC, graciegoheen commented on README.md
> +$ dbt run-operation generate_model_yaml --args '{"model_names": ["customers", "orders"]}'
Can you make all examples consistent? So either adjusting them all so they take `"model_names": ["customers", "orders"]` OR `"model_names": ["customers"]`

2022-11-03 23:00 UTC, angelica-lastra commented on README.md
> +$ dbt run-operation generate_model_yaml --args '{"model_names": ["customers", "orders"]}'
This makes sense now that we got rid of the string option!

2022-11-21 23:17 UTC, joellabes requested changes
A wording tweak and a potential bug, then this looks good to go!

2022-11-21 23:17 UTC, joellabes commented on macros/generate_model_yaml.sql
> +        {{ exceptions.raise_compiler_error("The name argument to ref() must be a list, got <class 'string'>: " ~ number) }}
This is a strange error message: 
- This doesn't seem to be an argument to ref, should that be `model_names`?
- What is `number`? I don't see it defined anywhere
- Saying `<class 'string'>` feels like the sort of thing that comes from an automatically-generated error message. 

Have taken a swing at an alternative, but lmk if I've misunderstood its purpose
```suggestion
        {{ exceptions.raise_compiler_error("The `model_names` argument must always be a list, even if there is only one model.") }}
```

2022-11-21 23:17 UTC, joellabes commented on macros/generate_model_yaml.sql
> +                {% set model_yaml = codegen.generate_column_yaml(column, model_yaml, column_desc_dict) %}
With this being a `set` instead of an `append`, won't it overwrite everything that's already in `model_yaml`? (I haven't tried this, but it looks weird)

2022-11-23 21:21 UTC, angelica-lastra commented on macros/generate_model_yaml.sql
> +                {% set model_yaml = codegen.generate_column_yaml(column, model_yaml, column_desc_dict) %}
Hi, Joel! Thank you for bringing this up, after discussing with @b-per and @graciegoheen we came to the conclusion that the code should read as is. The reason is that model_yaml is set to a macro that is recursive, which means that it will constantly be iterating and updating itself based on it as it goes through the loop. It took me some time to understand it but if we look at the macro above this one, it becomes a little clearer.

2022-11-23 21:27 UTC, angelica-lastra commented on macros/generate_model_yaml.sql
> +        {{ exceptions.raise_compiler_error("The name argument to ref() must be a list, got <class 'string'>: " ~ number) }}
Hi again, Joel! thank you for rewriting this, I was following this [exceptions.raise_compiler_error](https://docs.getdbt.com/reference/dbt-jinja-functions/exceptions) example and didn't know how far away from it I could wander. It has been fixed now!

2022-11-23 22:00 UTC, joellabes approved these changes

2022-11-23 22:00 UTC, merged

2022-11-23 22:01 UTC, joellabes commented
hurrah! congrats @angelica-lastra 🎉